# Generated by Django 3.2.5 on 2022-08-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao_nickname', models.CharField(max_length=128, unique=True)),
                ('university', models.CharField(max_length=128, null=True)),
                ('track', models.CharField(max_length=128, null=True)),
                ('username', models.CharField(max_length=10, null=True)),
                ('smallTalk', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
