# Generated by Django 3.2.5 on 2022-08-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='user_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='kakao_nickname',
            field=models.CharField(max_length=128),
        ),
    ]
