# Generated by Django 3.2.5 on 2022-08-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220803_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='token',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
