# Generated by Django 3.2.5 on 2022-08-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_accounts_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
